export const projectImg = [
    { img: "/images/Case_study_1.png" },
    { img: "/images/Case_study_2.png" },
    { img: "/images/Case_study_3.png" },
    { img: "/images/Case_study_4.png" },
    { img: "/images/Case_study_5.png" },
    { img: "/images/Case_study_6.png" },
    { img: "/images/Case_study_7.png" },
    { img: "/images/Case_study_8.png" },
    { img: "/images/Case_study_9.png" },
    { img: "/images/Case_study_10.png" },
    { img: "/images/Case_study_11.png" },
    { img: "/images/Case_study_12.png" },
    { img: "/images/Case_study_13.png" },
    { img: "/images/Case_study_14.png" },
    { img: "/images/Case_study_15.png" },
    { img: "/images/Case_study_16.png" },
    { img: "/images/Case_study_17.png" },
    { img: "/images/Case_study_18.png" },
    { img: "/images/Case_study_19.png" },
    { img: "/images/Case_study_20.png" },
    { img: "/images/Case_study_21.png" },
    { img: "/images/Case_study_22.png" },
    { img: "/images/Case_study_23.png" },
    { img: "/images/Case_study_24.png" },
    { img: "/images/Case_study_25.png" }
  ];